# Read about configuration here: https://jekyllrb.com/docs/configuration/options/
title: POAP Directory
description: POAP.directory is a collection of POAP products to help you find the tools you need.
keywords: poap, directory, resources, tools, projects, products
url: https://poap.directory
permalink: pretty # Do not change this, it will break all links
timezone: America/New_York
markdown: kramdown
livereload: true
port: 4400

# Global variables
primary_color: "#1C1C1C"
primary_color_shaded: "#000"

# Notifications
notification_enabled: false
notification_id: 1 # Increment value when new notification to show again
notification_msg: This is a test notification message.<br>This is a test notification message.

# Navigation
nav_enabled: true

# Links
github_repo: https://github.com/etheralpha/
discord_invite: 


